// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timekeeping.Repositories.Contexts;

namespace Timekeeping.Repositories.Migrations
{
    [DbContext(typeof(TimekeepingContext))]
    [Migration("20190613114809_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Timekeeping.Repositories.Abstractions.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("user_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("user_email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("user_name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(150);

                    b.HasKey("Id")
                        .HasName("pk_users_user_id");

                    b.HasIndex("Email")
                        .HasName("ix_users_user_email");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
